version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: linkedin-game-scores-db
    environment:
      POSTGRES_DB: gamescores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - game-scores-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./game.api
      dockerfile: Dockerfile
    container_name: linkedin-game-scores-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=gamescores;Username=postgres;Password=postgres
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - game-scores-network
    restart: unless-stopped

  client:
    build:
      context: ./game.client
      dockerfile: Dockerfile
    container_name: linkedin-game-scores-client
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - game-scores-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres

networks:
  game-scores-network:
    driver: bridge